import discord
from discord.ext import commands

class guidelines(commands.Cog):
	def __init__(self, client):
		self.client = client

	@commands.command()
	async def guidelines(self, ctx, *args):
		if len(args) == 0:
			embedMessageDescription1 = "[***Discord Community Guidelines***](https://discord.com/guidelines)\n**Last Updated: May 19th, 2020.**\n\nWe created Discord to help people come together around games. It's been amazing to watch it grow into what it is today - a place where millions of diverse communities exist and people connect with old friends and new. We can't wait to see what's next.\n\nOur community guidelines are meant to explain what is and isn’t allowed on Discord, and ensure that everyone has a good experience. If you come across a message that appears to break these rules, please report it to us. We may take a number of steps, including issuing a warning, removing the content, or removing the accounts and/or servers responsible.\n\nThe overwhelming majority of people use Discord responsibly, so these guidelines may seem obvious. Still, we want to be clear about the expectations for our users. Every user of Discord should feel like their voice can be heard, but not at the expense of someone else.\n\nThere are 3 pages for each section! If you're interested, please type\:\n```e!guidelines [PAGE]```"
			embedMessage1 = discord.Embed(title="Mitsuha Miyamizu Discord Bot - Original Discord Guidelines",url="https://discord.com/guidelines",description=embedMessageDescription1, color=discord.Colour.from_rgb(255,182,193))
			await ctx.send(embed=embedMessage1)
		elif len(args) == 1:
			if args[0] == "1":
				embedMessageDescription2 = "1. **Do not organize, participate in, or encourage harassment of others.** Disagreements happen and are normal, but continuous, repetitive, or severe negative comments may cross the line into harassment and are not okay.\n2. **Do not organize, promote, or coordinate servers around hate speech.** It’s unacceptable to attack a person or a community based on attributes such as their race, ethnicity, national origin, sex, gender, sexual orientation, religious affiliation, or disabilities.\n3. **Do not make threats of violence or threaten to harm others.** This includes indirect threats, as well as sharing or threatening to share someone’s private personal information (also known as doxxing).\n4. **Do not evade user blocks or server bans.** Do not send unwanted, repeated friend requests or messages, especially after they’ve made it clear they don’t want to talk to you anymore. Do not try to hide your identity in an attempt to contact someone who has blocked you, or otherwise circumvent the tools we have which enable users to protect themselves.\n5. **Do not send others viruses or malware**, attempt to phish others, or hack or DDoS them."
				embedMessage2 = discord.Embed(title="Here are some rules for interacting with others:",url="https://discord.com/guidelines",description=embedMessageDescription2, color=discord.Colour.from_rgb(255,182,193))
				embedMessage2.set_footer(text="Page 1/3 of the Discord Guidelines")
			elif args[0] == "2":
				embedMessageDescription2 = "6. **You must apply the NSFW label to channels if there is adult content in that channel.** Any content that cannot be placed in an age-gated channel, such as avatars, server banners, and invite splashes, may not contain adult content.\n7. **You may not sexualize minors in any way.** This includes sharing content or links which depict minors in a pornographic, sexually suggestive, or violent manner, and includes illustrated or digitally altered pornography that depicts minors (such as lolicon, shotacon, or cub). We report illegal content to the National Center for Missing and Exploited Children.\n8. **You may not share sexually explicit content of other people without their consent**, or share or promote sharing of non-consensual intimate imagery (also known as revenge porn) in an attempt to shame or degrade someone.\n9. **You may not share content that glorifies or promotes suicide or self-harm**, including any encouragement to others to cut themselves, or embrace eating disorders such as anorexia or bulimia.\n10. **You may not share images of sadistic gore or animal cruelty.**\n11. **You may not use Discord for the organization, promotion, or support of violent extremism.**\n12. **You may not operate a server that sells or facilitates the sales of prohibited or potentially dangerous goods.** This includes firearms, ammunition, drugs, and controlled substances.\n13. **You may not promote, distribute, or provide access to content involving the hacking, cracking, or distribution of pirated software or stolen accounts.** This includes sharing or selling cheats or hacks that may negatively affect others in multiplayer games.\n14. In general, **you should not promote, encourage or engage in any illegal behavior.** This is very likely to get you kicked off Discord, and may get you reported to law enforcement."
				embedMessage2 = discord.Embed(title="Here are some rules for content on Discord:",url="https://discord.com/guidelines",description=embedMessageDescription2, color=discord.Colour.from_rgb(255,182,193))
				embedMessage2.set_footer(text="Page 2/3 of the Discord Guidelines")
			elif args[0] == "3":
				embedMessageDescription2 = "15. **You may not sell your account or your server.**\n16. **You may not use self-bots or user-bots to access Discord.**\n17. **You may not share content that violates anyone's intellectual property or other rights.**\n18. **You may not spam Discord**, especially our Customer Support and Trust & Safety teams. Making false and malicious reports, sending multiple reports about the same issue, or asking a group of users to all report the same content may lead to action being taken on your account."
				embedMessage2 = discord.Embed(title="Finally, we ask that you respect Discord itself:",url="https://discord.com/guidelines",description=embedMessageDescription2, color=discord.Colour.from_rgb(255,182,193))
				embedMessage2.set_footer(text="Page 3/3 of the Discord Guidelines")
			else:
				embedMessageDescription2 = "❌ | \"**" + args[0] + "**\" doesn\'t exist as a page number in this command!"
				embedMessage2 = discord.Embed(title="Error with arguments!",description=embedMessageDescription2, color=discord.Colour.from_rgb(255,182,193))
			await ctx.send(embed=embedMessage2)

def setup(client):
	client.add_cog(guidelines(client))